### ISSUE TITLE
ERROR    | __main__:connect_to_wss:64

### ISSUE THREAD

**Issue by billal7** [Solana0x/GrassNode#12]
2024-09-27 13:46:43.725 | ERROR    | __main__:connect_to_wss:64 - Error with proxy {proxy} : Invalid scheme component: billal097fcpqnsta1whl-session-2qmvxs3d-package-residential

**Comment by Solana0x** [comment]
use properly ! 

socks5://Username:pass@ip:port

**Comment by billal7** [comment]
it is absolutely in socks5://username:pass@ip:port  this format but still same error.

**Comment by Solana0x** [comment]
Invalid scheme component

only comes when proxy is in wrong formate ! can you show which plan you bought?

**Comment by Solana0x** [comment]
Nah Buy ISP plan
this one no longer works mate

**Comment by billal7** [comment]
:(  I'm poor now

**Comment by Solana0x** [comment]
https://app.proxies.fo/purchase/isp

"you can buy anyone "

![image](https://github.com/user-attachments/assets/767c5850-29cb-4dd2-929f-228a5fa7d31a)

**Comment by billal7** [comment]
ok

**Comment by billal7** [comment]
any coupon?

**Comment by billal7** [comment]
![Screenshot 2024-09-27 200835](https://github.com/user-attachments/assets/bf3fb8cd-0413-4f11-9384-5f6db8faf056)

00 points showing even in epoch earning and todays earning. today's earning was few but now it's 00. is there anything I need to understand?

**Comment by Solana0x** [comment]
it will show 00 untill next day please wait untill next days 10:30 AM UTC ! After that points are added ! so to get an avg idea you should wait atleast 1-2 days !

**Comment by billal7** [comment]
thank you, I can't find you in discord with the provided link.
