### ISSUE TITLE
How to ADD Mutiple ID 

### ISSUE THREAD

**Issue by 0xsiwant** [Solana0x/GrassNode#3]
Hi **solana0x**,
I would like to extend my sincerest thanks for your hard work in creating this script. I greatly appreciate the effort and dedication you have put into this project.
Additionally, I have a question regarding the addition of IDs, specifically how to add multiple IDs for several accounts. I noticed that there is no detailed explanation about this in the README. I would be very grateful if you could provide some additional guidance or instructions on this matter.

**Once again, thank you very much!**

**Comment by Solana0x** [comment]
if you wanted to Add multiple grass id just copy the python script file and then name it as ID1.py so on .. and name the Proxy1.txt ... proxy2.txt and so on...

and run the files !! you can use screen or pm2 or tmux sessions to run multiple in background
