### ISSUE TITLE
Unable to DM 

### ISSUE THREAD

**Issue by ankitraz151** [Solana0x/GrassNode#4]
Sir , Unable to DM you on discord . When i click the link it takes me to my profile only . Please Mention your Discord UserId

**Comment by Solana0x** [comment]
0xPhantom

**Comment by Solana0x** [comment]
![image](https://github.com/Solana0x/GrassNode/assets/142747768/ffb02f28-4b5d-4130-a925-a65f31845bc9)
its mentioned along with the link !

**Comment by ankitraz151** [comment]
My bad Sir 

Thanxx for Responding :)
