### ISSUE TITLE
UPDATE CODE please

### ISSUE THREAD

**Issue by 0xsiwant** [Solana0x/GrassNode#6]
All proxy now not work again with the code . please update , thanks

**Comment by Solana0x** [comment]
its working fine Mate Please drop your questions or errors below i am running the same code over multiple accounts along with me many other people running same 

![image](https://github.com/Solana0x/GrassNode/assets/142747768/8acb55c8-fa49-4e94-a576-69cbb2ca136b)

**Comment by 0xsiwant** [comment]
![image](https://github.com/Solana0x/GrassNode/assets/129720275/2e7400a0-8c56-4993-9362-5e44ccf7522b)
![image](https://github.com/Solana0x/GrassNode/assets/129720275/be653759-18a1-4bfd-9593-3607567a9cbb)

what proxy do you use, I used proxies.fo as you mentioned, but now everything is erroring. I don't know why, even though 3 days ago it was fine, and everything went fine

**Comment by 0xsiwant** [comment]
how come you get 200-800k? 
3 days ago I only got 35k, even though my proxy was 5000 proxies

but now I only get 124 Grass points, because all proxy errors are like that

**Comment by Solana0x** [comment]
i am running in vps and isnt closing the code i am running in several accounts i just ran 75 proxies and proxy.txt there are 1000 proxies ! may be there could be error from proxyfo site recenltly my earnings were also little down. 

Probably try some other Proxy sellers the cheapest i could find in knowledge was This only

**Comment by aangps01** [comment]
@Solana0x is there any recommendation for proxy seller alternative?

**Comment by Solana0x** [comment]
Myself i searched many but cheapest is proxiesfo only rest idk others .

**Comment by 0xsiwant** [comment]
> i am running in vps and isnt closing the code i am running in several accounts i just ran 75 proxies and proxy.txt there are 1000 proxies ! may be there could be error from proxyfo site recenltly my earnings were also little down.
> 
> Probably try some other Proxy sellers the cheapest i could find in knowledge was This only

I have some questions regarding bandwidth usage. For running 75 scripts with 1000 proxies per script, how much bandwidth (in GB) do you usually purchase for one day? I bought 1GB of residential bandwidth, but it gets consumed within 2-3 hours. Is there something wrong with my settings?

Thank you.

**Comment by trunghuyne** [comment]
me 
![image](https://github.com/Solana0x/GrassNode/assets/119916277/b234ff1b-ef3d-4338-9f42-9fa0c04a41cc)

**Comment by Solana0x** [comment]
is that nodepay ? @trunghuyne

**Comment by Solana0x** [comment]
Never got http 404 error may be wait for sometime

**Comment by Solana0x** [comment]
> I have some questions regarding bandwidth usage. For running 75 scripts with 1000 proxies per script, how much bandwidth (in GB) do you usually purchase for one day? I bought 1GB of residential bandwidth, but it gets consumed within 2-3 hours. Is there something wrong with my settings?
> 
> Thank

Last time i ran i used to spend 1.2-1.5GB for 2-3M points roughly but i am running 24/7 in a vps as said in the github repo !! 

Also its strange that 1GB is consumed within 2-3 hrs i switched proxy seller some days ago to a new website but they turned off their ports for Grass new users . SO, new users cant signup their else their service is much better i could have suggested that !!

may be open support ticket or give me 3-4 days to test with proxyfo then i can give an Answer with the current situation ! 
when i created the code for grass at that time the config and earnings were same as indicated ! even earning gone better with time and code also got a lot better ....

**Comment by Solana0x** [comment]
https://github.com/Solana0x/GrassNode/issues/5#issuecomment-2209498249

**Comment by trunghuyne** [comment]
I just tried again. It is working now.
![image](https://github.com/Solana0x/GrassNode/assets/119916277/16885c60-7ff5-4d8c-afbd-e9a7127526aa)

**Comment by Solana0x** [comment]
Great ! @trunghuyne

**Comment by ptrgiang** [comment]
Hi @Solana0x, after running with proxies bought from proxies.fo (as you mentioned), my grass points keep decreasing. Do you have the same problem? From 10k (run locally) to 5k (with proxies)...

**Comment by Solana0x** [comment]
Points that are gone are temporary if you run script in a Good VPS with 0% interruption then there wont be any issue !! 

@ptrgiang

**Comment by Solana0x** [comment]
if there any issue kindly open another request or you can contact me directly through Discord
