### ISSUE TITLE
Automatically removes the dead proxy from the File

### ISSUE THREAD

**Issue by bbqspeed** [Solana0x/GrassNode#7]
Can you add a switch to enable this feature? Because I am using a fixed IP network, sometimes the quality is not very good. I can try again, but I don't want it to be automatically deleted from the text

**Comment by Solana0x** [comment]
ok i will add code where it dont delete proxy

**Comment by Solana0x** [comment]
@bbqspeed added that code under [no_delete_proxy.py](https://github.com/Solana0x/GrassNode/blob/main/no_delete_proxy.py)
